version: '3.1'
services:
  extractor:
    image: extractor:0.2
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka

  searcherScholar:
    image: searcher_scholar:0.1    
    restart: always
    #ports:
    #  - 8081:8081
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    #ports:
    #  - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    #    ports:         Fare il mapping su questa porta solo se KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    #  - 9092:9092      per motivi _dev
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
